#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>

#include "sdf/generator.h"
#include "sdf/obj_writer.h"
#include "sdf/scene.h"

namespace
{

void expect_true(bool condition, const std::string &message)
{
  if (!condition)
  {
    throw std::runtime_error(message);
  }
}

void test_frame_scene_layout()
{
  const sdf::SceneDocument scene = sdf::make_frame_006_blockout_scene();

  expect_true(scene.name == "frame_006_blockout", "scene should keep a stable blockout name");
  expect_true(scene.boxes.size() == 14, "frame_006 blockout should contain 14 boxes in the initial slice");
}

void test_csg_opening_flips_the_sign()
{
  const sdf::SceneDocument scene = sdf::make_frame_006_blockout_scene();

  const float tower_mass = sdf::evaluate_scene_sdf(scene, {-18.0f, 10.0f, 18.0f});
  const float opening_center = sdf::evaluate_scene_sdf(scene, {-18.0f, 20.0f, 18.0f});

  expect_true(tower_mass < 0.0f, "left tower body should remain inside the solid");
  expect_true(opening_center > 0.0f, "subtractive opening should carve a positive pocket");
}

void test_mesh_generation_produces_triangles()
{
  const sdf::SceneDocument scene = sdf::make_frame_006_blockout_scene();
  sdf::BuildSettings settings = sdf::make_frame_006_build_settings();
  settings.cell_size = 2.0f;

  const sdf::SceneBuildResult build = sdf::build_scene_mesh(scene, settings);

  expect_true(build.sampled_cells > 0, "mesh build should sample at least one cell");
  expect_true(build.occupied_cells > 0, "mesh build should mark occupied voxels");
  expect_true(!build.mesh.vertices.empty(), "mesh build should emit vertices");
  expect_true(!build.mesh.triangles.empty(), "mesh build should emit triangles");
  expect_true((build.mesh.vertices.size() % 4) == 0, "voxel face emission should append four vertices per face");
  expect_true((build.mesh.triangles.size() % 2) == 0, "voxel face emission should append two triangles per face");
}

void test_obj_writer_emits_a_file()
{
  const sdf::SceneDocument scene = sdf::make_frame_006_blockout_scene();
  sdf::BuildSettings settings = sdf::make_frame_006_build_settings();
  settings.cell_size = 3.0f;

  const sdf::SceneBuildResult build = sdf::build_scene_mesh(scene, settings);
  const std::filesystem::path output_path = std::filesystem::current_path() / "test_output" / "frame_006_blockout.obj";

  std::string error_message;
  const bool ok = sdf::write_obj(build.mesh, output_path, &error_message);

  expect_true(ok, "obj export should succeed");
  expect_true(std::filesystem::exists(output_path), "obj export should create a file");
  expect_true(std::filesystem::file_size(output_path) > 0, "obj output should not be empty");

  std::ifstream stream(output_path);
  std::string first_line;
  std::getline(stream, first_line);
  expect_true(first_line == "# Generated by sdf_cli", "obj file should start with the generator banner");
}

}  // namespace

int main()
{
  try
  {
    test_frame_scene_layout();
    test_csg_opening_flips_the_sign();
    test_mesh_generation_produces_triangles();
    test_obj_writer_emits_a_file();
  }
  catch (const std::exception &exception)
  {
    std::cerr << "Test failure: " << exception.what() << '\n';
    return 1;
  }

  std::cout << "All sdf tests passed.\n";
  return 0;
}
