#include "sdf/obj_writer.h"

#include <filesystem>
#include <fstream>
#include <iomanip>
#include <system_error>

namespace sdf
{

namespace
{

bool write_material_library(
  const std::filesystem::path &obj_output_path,
  const ObjWriteOptions &options,
  std::string *error_message)
{
  if (options.diffuse_texture_path.empty())
  {
    return true;
  }

  std::filesystem::path material_path = obj_output_path;
  material_path.replace_extension(".mtl");
  std::ofstream material_stream(material_path, std::ios::out | std::ios::trunc);
  if (!material_stream.is_open())
  {
    if (error_message != nullptr)
    {
      *error_message = "failed to open mtl output file";
    }
    return false;
  }

  std::filesystem::path diffuse_texture_reference = options.diffuse_texture_path;
  std::error_code relative_error;
  if (options.diffuse_texture_path.is_absolute())
  {
    diffuse_texture_reference = std::filesystem::relative(
      options.diffuse_texture_path,
      material_path.parent_path(),
      relative_error);
    if (relative_error)
    {
      diffuse_texture_reference = options.diffuse_texture_path.filename();
    }
  }

  const std::string material_name = options.material_name.empty() ? "ao_preview" : options.material_name;

  material_stream << "# Generated by sdf_cli\n";
  material_stream << "newmtl " << material_name << '\n';
  material_stream << "Ka 0.000000 0.000000 0.000000\n";
  material_stream << "Kd 1.000000 1.000000 1.000000\n";
  material_stream << "Ks 0.000000 0.000000 0.000000\n";
  material_stream << "d 1.000000\n";
  material_stream << "illum 1\n";
  material_stream << "map_Kd " << diffuse_texture_reference.generic_string() << '\n';

  if (!material_stream.good())
  {
    if (error_message != nullptr)
    {
      *error_message = "failed while writing mtl contents";
    }
    return false;
  }

  return true;
}

}  // namespace

bool write_obj(
  const Mesh &mesh,
  const std::filesystem::path &output_path,
  const ObjWriteOptions &options,
  std::string *error_message)
{
  if (!output_path.has_parent_path())
  {
    if (error_message != nullptr)
    {
      error_message->clear();
    }
  }
  else
  {
    std::error_code create_error;
    std::filesystem::create_directories(output_path.parent_path(), create_error);

    if (create_error)
    {
      if (error_message != nullptr)
      {
        *error_message = "failed to create output directory";
      }
      return false;
    }
  }

  if (!write_material_library(output_path, options, error_message))
  {
    return false;
  }

  std::ofstream stream(output_path, std::ios::out | std::ios::trunc);

  if (!stream.is_open())
  {
    if (error_message != nullptr)
    {
      *error_message = "failed to open obj output file";
    }
    return false;
  }

  stream << "# Generated by sdf_cli\n";
  if (!options.diffuse_texture_path.empty())
  {
    std::filesystem::path material_path = output_path;
    material_path.replace_extension(".mtl");
    stream << "mtllib " << material_path.filename().generic_string() << '\n';
  }
  stream << "o " << (options.object_name.empty() ? "blockout" : options.object_name) << '\n';
  if (!options.diffuse_texture_path.empty())
  {
    stream << "usemtl " << (options.material_name.empty() ? "ao_preview" : options.material_name) << '\n';
  }
  stream << std::fixed << std::setprecision(6);

  for (const MeshVertex &vertex : mesh.vertices)
  {
    stream << "v " << vertex.position.x << ' ' << vertex.position.y << ' ' << vertex.position.z << '\n';
  }

  for (const MeshVertex &vertex : mesh.vertices)
  {
    stream << "vt " << vertex.uv0.x << ' ' << vertex.uv0.y << '\n';
  }

  for (const MeshVertex &vertex : mesh.vertices)
  {
    stream << "vn " << vertex.normal.x << ' ' << vertex.normal.y << ' ' << vertex.normal.z << '\n';
  }

  for (const MeshTriangle &triangle : mesh.triangles)
  {
    const std::uint32_t i0 = triangle.i0 + 1;
    const std::uint32_t i1 = triangle.i1 + 1;
    const std::uint32_t i2 = triangle.i2 + 1;

    stream << "f "
           << i0 << '/' << i0 << '/' << i0 << ' '
           << i1 << '/' << i1 << '/' << i1 << ' '
           << i2 << '/' << i2 << '/' << i2 << '\n';
  }

  if (!stream.good())
  {
    if (error_message != nullptr)
    {
      *error_message = "failed while writing obj contents";
    }
    return false;
  }

  return true;
}

}  // namespace sdf
