#include "sdf/obj_writer.h"

#include <filesystem>
#include <fstream>
#include <iomanip>

namespace sdf
{

bool write_obj(const Mesh &mesh, const std::filesystem::path &output_path, std::string *error_message)
{
  if (!output_path.has_parent_path())
  {
    if (error_message != nullptr)
    {
      error_message->clear();
    }
  }
  else
  {
    std::error_code create_error;
    std::filesystem::create_directories(output_path.parent_path(), create_error);

    if (create_error)
    {
      if (error_message != nullptr)
      {
        *error_message = "failed to create output directory";
      }
      return false;
    }
  }

  std::ofstream stream(output_path, std::ios::out | std::ios::trunc);

  if (!stream.is_open())
  {
    if (error_message != nullptr)
    {
      *error_message = "failed to open obj output file";
    }
    return false;
  }

  stream << "# Generated by sdf_cli\n";
  stream << "o blockout\n";
  stream << std::fixed << std::setprecision(6);

  for (const MeshVertex &vertex : mesh.vertices)
  {
    stream << "v " << vertex.position.x << ' ' << vertex.position.y << ' ' << vertex.position.z << '\n';
  }

  for (const MeshVertex &vertex : mesh.vertices)
  {
    stream << "vt " << vertex.uv0.x << ' ' << vertex.uv0.y << '\n';
  }

  for (const MeshVertex &vertex : mesh.vertices)
  {
    stream << "vn " << vertex.normal.x << ' ' << vertex.normal.y << ' ' << vertex.normal.z << '\n';
  }

  for (const MeshTriangle &triangle : mesh.triangles)
  {
    const std::uint32_t i0 = triangle.i0 + 1;
    const std::uint32_t i1 = triangle.i1 + 1;
    const std::uint32_t i2 = triangle.i2 + 1;

    stream << "f "
           << i0 << '/' << i0 << '/' << i0 << ' '
           << i1 << '/' << i1 << '/' << i1 << ' '
           << i2 << '/' << i2 << '/' << i2 << '\n';
  }

  if (!stream.good())
  {
    if (error_message != nullptr)
    {
      *error_message = "failed while writing obj contents";
    }
    return false;
  }

  return true;
}

}  // namespace sdf
